---
- hosts: backup
  become: true
  vars:
    user: borg
    group: borg
    home: /home/borg

  tasks:    
    - name: Установка временной зоны MSK
      timezone:
        name: Europe/Moscow

    - name: Устанавливаем epel-репозиторий
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: Устанавливаем необходимые и вспомогательные пакеты через yum
      become: true
      yum:
        name: "{{item}}"
        state: present
      loop:
        - mc
        - nano
        - net-tools
        - yum-utils

    - name: Устанавливаем borgbackup 1.1.14
      get_url:
        url: https://github.com/borgbackup/borg/releases/download/1.1.14/borg-linux64
        dest: /usr/bin/borg
        owner: root
        group: root
        mode: '0755'
        
    - name: Группа пользователя borg
      group:
        name: "{{ group }}"
        state: present

    - name: Добавление пользователя borg
      user:
        name: "{{ user }}"
        home: "{{ home }}"
        createhome: yes
        group: "{{ group }}"
        state: present

    - name: добавляем директорию ssh
      file:
        path: "{{ home }}/.ssh"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0700
        state: directory

    - name: добавляем ssh-ключ
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', 'ssh/id_rsa.pub') }}"

    - name: меняем владельца
      file:
        path: "{{ home }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes

- name: server | Install and configure server
  hosts: server
  become: true

  tasks:
    - name: Получаем публичный ключ
      command: "ssh-keyscan -H 192.168.10.11"
      register: backupkey

    - name: Добавляем хост backup в известные хосты
      copy:
        content: "{{ backupkey.stdout }}"
        dest: /root/.ssh/known_hosts

    - name: Инициируем бэкапирование borg
      command: borg init -e none borg@192.168.10.11.:server-etc/
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
