---
- hosts: backup
  become: true
  vars:
    user: borg
    group: borg
    home: /home/borg

  tasks:    
    - name: timezone - Установка временной зоны MSK
      timezone:
        name: Europe/Moscow

    - name: install epel-release - Устанавливаем epel-репозиторий
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: install packages via yum - Устанавливаем необходимые и вспомогательные пакеты через yum
      become: true
      yum:
        name: "{{item}}"
        state: present
      loop:
        - mc
        - nano
        - net-tools
        - yum-utils

    - name: install borg backup package - Устанавливаем borgbackup 1.1.14
      get_url:
        url: https://github.com/borgbackup/borg/releases/download/1.1.14/borg-linux64
        dest: /usr/bin/borg
        owner: root
        group: root
        mode: '0755'
        
    - name: group create - Группа пользователя borg
      group:
        name: "{{ group }}"
        state: present

    - name: create borg user - Добавление пользователя borg
      user:
        name: "{{ user }}"
        home: "{{ home }}"
        createhome: yes
        group: "{{ group }}"
        state: present

    - name: create folder for ssh keys - добавляем директорию ssh
      file:
        path: "{{ home }}/.ssh"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0700
        state: directory

    - name: add ssh keys - добавляем ssh-ключ
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', 'ssh/id_rsa.pub') }}"

    - name: change folder's owner - меняем владельца
      file:
        path: "{{ home }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes

    - name: change folder's owner - меняем владельца
      file:
        path: /var/backup
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 01777

- name: server | Install and configure server
  hosts: server
  become: true

  tasks:
    - name: get public key -  публичный ключ
      command: "ssh-keyscan -H 192.168.10.11"
      register: backupkey

    - name: add backup host in known - Добавляем хост backup в известные хосты
      copy:
        content: "{{ backupkey.stdout }}"
        dest: /root/.ssh/known_hosts

    - name: create borg init - Инициируем бэкапирование borg
      command: sh /home/vagrant/borginit.sh
   
    - name: Копируем правило logrotate
      copy:
        src: borg
        dest: /etc/logrotate.d/borg



     
        
        
        
        
        
        
        
        
        
        
        
        
        
        
