---
- hosts: server
  become: true

  tasks:
#    - name: Отключаем SELinux (на всякий случай)
#      selinux:
#        state: disabled
               
    - name: Установка временной зоны MSK
      timezone:
        name: Europe/Moscow

    - name: Устанавливаем epel-репозиторий
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: Устанавливаем необходимые и вспомогательные пакеты через yum
      become: true
      yum:
        name: "{{item}}"
        state: present
      loop:
        - mc
        - nano
        - net-tools
        - yum-utils


    - name: Устанавливаем borgbackup 1.1.14
      get_url:
        url: https://github.com/borgbackup/borg/releases/download/1.1.14/borg-linux64
        dest: /usr/bin/borg
        owner: root
        group: root
        mode: '0777'

    - name: Копируем скрипт
      copy:
        src: backup-borg.sh
        dest: /opt/backup-borg.sh
        owner: vagrant
        group: vagrant
        mode: a+x

    - name: ensure file exists
      copy:
        content: ""
        dest: /var/log/backup_borg.log
        force: no
        group: vagrant
        owner: vagrant
        mode: 0777

    - name: Копируем unit service
      copy:
        src: backup-borg.service
        dest: /etc/systemd/system/backup-borg.service
      notify:
        - enable backup-borg.service

    - name: Копируем unit timer
      copy:
        src: backup-borg.timer
        dest: /etc/systemd/system/
      notify:
        - enable backup-borg.timer
        
  handlers:
    - name: enable backup-borg.timer
      systemd:
        name: backup-borg.timer
        daemon_reload: true
        state: restarted
        enabled: true
        
    - name: enable backup-borg.service
      systemd:
        name: backup-borg.service
        daemon_reload: true
        enabled: true

