---
- hosts: backup
  become: true

  tasks:    
    - name: Установка временной зоны MSK
      timezone:
        name: Europe/Moscow

    - name: Устанавливаем epel-репозиторий
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: Устанавливаем необходимые и вспомогательные пакеты через yum
      become: true
      yum:
        name: "{{item}}"
        state: present
      loop:
        - mc
        - nano
        - net-tools
        - yum-utils

    - name: Устанавливаем borgbackup 1.1.14
      get_url:
        url: https://github.com/borgbackup/borg/releases/download/1.1.14/borg-linux64
        dest: /usr/bin/borg
        owner: root
        group: root
        mode: '0777'
